name: Ansible Deployment

on:
  push:
    branches: ["main"]
    paths:
      - 'ansible/Projet_Kasm'

jobs:
  ansible-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini install_docker.yml --become
